apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nestjs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestjs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: nestjs 
  labels:
    app: nestjs
spec: 
  selector:
    app: nestjs
  ports:
    - name: service-port
      port: 5153
      targetPort: 8184
  type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nestjs 
  labels:
    app: nestjs
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: deployment-port
          image: edgareor/nestjs-rest-nodejs-mongodb-docker-2023:version1
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8184
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits: 
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: VAR_TEST
              value: "valorTest"